controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute

ficha_new:
  path: /ficha/new
  controller: App\Controller\FichaController::new
  methods: [POST]

ficha_find:
  path: /ficha/find/{id}
  controller: App\Controller\FichaController::findById
  methods: [GET]

ficha_update:
  path: /ficha/update/{id}
  controller: App\Controller\FichaController::update
  methods: [PUT]

ficha_delete:
  path: /ficha/delete/{id}
  controller: App\Controller\FichaController::delete
  methods: [DELETE]

ficha_find_all:
  path: /ficha/find-all
  controller: App\Controller\FichaController::findAll
  methods: [GET]
